// src/app/layout.tsx
import type { Metadata } from "next";
import { Montserrat } from "next/font/google"; // <-- Pastikan ini diimpor
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

// Setup font Montserrat
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "700", "800"], 
});

export const metadata: Metadata = {
  title: "KN Fitness - Your All-in Gym Experience", 
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Pastikan className di body ini benar */}
      <body
        className={`${montserrat.variable} antialiased`}
      >
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}